export const jobDetails = [
  {
    Title: 'UI/UX Designer',
    Company: 'Great Vibes - Information Technology',
    Location: 'Chennai, TamilNadu, India(In-Office)',
    jobType: 'Part-Time(9.00am-5.00pm IST)',
    Experience: 'Experience (1 - 2 years)',
    CTC: 'INR (₹) 30,000 - 50,000 / Month',
    Employees: '51-200 employees',
  },
  {
    Title: 'Developer',
    Company: 'Great Vibes - Information Technology',
    Location: 'Chennai, TamilNadu, India(In-Office)',
    jobType: 'Part-Time(9.00am-5.00pm IST)',
    Experience: 'Experience (1 - 2 years)',
    CTC: 'INR (₹) 50,000 - 70,000 / Month',
    Employees: '51-200 employees',
  },
  {
    Title: 'Interaction Designer',
    Company: 'Great Vibes - Information Technology',
    Location: 'Chennai, TamilNadu, India(In-Office)',
    jobType: 'Part-Time(9.00am-5.00pm IST)',
    Experience: 'Experience (1 - 2 years)',
    CTC: 'INR (₹) 30,000 - 50,000 / Month',
    Employees: '51-200 employees',
  },
  {
    Title: 'SEO Analyst',
    Company: 'Great Vibes - Information Technology',
    Location: 'Chennai, TamilNadu, India(In-Office)',
    jobType: 'Part-Time(9.00am-5.00pm IST)',
    Experience: 'Experience (1 - 2 years)',
    CTC: 'INR (₹) 30,000 - 50,000 / Month',
    Employees: '51-200 employees',
  },
];
